import pandas as pd
from pathlib import Path


def test_normalize_headers():
    from app import normalize_headers
    cols = ['Season', 'Style-CW', 'Thread-Color', 'SAP Codes', 'Consumption in CO']
    result = normalize_headers(cols)
    assert result['Season'] == 'Season'
    assert result['Style-CW'] == 'Style-CW'
    assert result['Thread-Color'] == 'Thread-Color'
    assert result['SAP Codes'] == 'SAP Codes'
    assert result['Consumption in CO'] == 'Consumption in CO'


def test_build_master_db_includes_nested_subfolders(tmp_path):
    from app import build_master_db

    root = tmp_path / 'THREAD DB FOR FORECAST'
    child_folder = root / 'FA26'
    child_folder.mkdir(parents=True)

    workbook_path = child_folder / 'sample.xlsx'
    frame = pd.DataFrame([
        {'Season': 'FA26', 'Style-CW': 'A001', 'Thread-Color': 'Red', 'SAP Codes': '1001', 'Consumption in CO': 12}
    ])
    with pd.ExcelWriter(workbook_path, engine='openpyxl') as writer:
        frame.to_excel(writer, index=False, sheet_name='Sheet1')

    master_db, metadata_log = build_master_db(str(root))

    assert not master_db.empty
    assert 'FA26' in master_db['Source Folder'].tolist()
    assert any(entry.get('status') == 'ok' for entry in metadata_log)


def test_build_master_db_merges_consumption_variants_into_one_column(tmp_path):
    from app import build_master_db

    root = tmp_path / 'THREAD DB FOR FORECAST'
    child_folder = root / 'FA26'
    child_folder.mkdir(parents=True)

    workbook_path = child_folder / 'sample.xlsx'
    frame = pd.DataFrame([
        {'Season': 'FA26', 'Style-CW': 'A001', 'Thread-Color': 'Red', 'SAP Codes': '1001', 'Consumption in CO': 12, 'Sum of Consumption in CO': 20}
    ])
    with pd.ExcelWriter(workbook_path, engine='openpyxl') as writer:
        frame.to_excel(writer, index=False, sheet_name='Sheet1')

    master_db, _ = build_master_db(str(root))

    assert 'Consumption in CO' in master_db.columns
    assert 'Consumption in CO_2' not in master_db.columns
    assert master_db.loc[0, 'Consumption in CO'] == '12'


def test_build_master_db_detects_header_after_preamble_row(tmp_path):
    from app import build_master_db

    root = tmp_path / 'THREAD DB FOR FORECAST'
    child_folder = root / 'FA26'
    child_folder.mkdir(parents=True)

    workbook_path = child_folder / 'sample.xlsx'
    with pd.ExcelWriter(workbook_path, engine='openpyxl') as writer:
        sheet = writer.book.create_sheet('Thread_DB')
        sheet.append(['Generated by test'])
        sheet.append(['Season', 'Style-CW', 'Thread-Color', 'SAP Codes', 'Consumption in CO'])
        sheet.append(['FA26', 'A001', 'Red', '1001', '12'])

    master_db, metadata_log = build_master_db(str(root))

    assert not master_db.empty
    assert master_db.loc[0, 'Season'] == 'FA26'
    assert any(entry.get('status') == 'ok' for entry in metadata_log)
